# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection

# Connection url for the database "netgloo_blog"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sports?useUnicode=true&characterEncoding=UTF-8
    username : root
    password :

   #数据库连接池配置
    max-active: 200
    max-idle: 100
    min-idle: 50
    initial-size: 20
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    validation-query: select 1
    #每10分钟收集空闲连接，单位毫秒
    time-between-eviction-runs-millis: 600000
    #连接的最大空闲时间，单位毫秒，60分钟
    min-evictable-idle-time-millis: 3600000
    max-wait: 60000

# ===============================
# = JPA / HIBERNATE
# ===============================

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect : org.hibernate.dialect.MySQL5Dialect

server:
  port: 7070